/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class wavelet_utils_Wavelet */

#ifndef _Included_wavelet_utils_Wavelet
#define _Included_wavelet_utils_Wavelet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wavelet_utils_Wavelet
 * Method:    linearSmooth5
 * Signature: ([DI)[D
 *
 * 五点三次平滑算法
 * 
 */
JNIEXPORT jdoubleArray JNICALL Java_wavelet_utils_Wavelet_linearSmooth5
  (JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     wavelet_utils_Wavelet
 * Method:    waveletFilter
 * Signature: ([DI)[D
 *
 * 小波变换低频滤波器
 */
JNIEXPORT jdoubleArray JNICALL Java_wavelet_utils_Wavelet_waveletFilter
  (JNIEnv *, jobject, jdoubleArray, jint);

/*
* Class:     wavelet_utils_Wavelet
* Method:    medianFilter
* Signature: ([DI)[D
*
* 中值滤波算法
*/
JNIEXPORT jdoubleArray JNICALL Java_wavelet_utils_Wavelet_medianFilter
(JNIEnv *, jobject, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
